sudo: required
services:
  - docker
env:  # setting global environment variables
  global:
    - SHA=$(git rev-parse HEAD) # getting the current commit sha and saving it in the SHA environment variable

     # to configure google cloud CLI and make sure it does not try to show any prompts that require user input
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # download and install the google cloud sdk, "bash > /dev/null will install the google cloud sdk in our travis instance"
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # go to the default installed directory for google cloud and look for the path.bash.basic file 
  - source $HOME/google-cloud-sdk/path.bash.inc
  # make sure the google cloud sdk will install the kubectl command
  - gcloud components update kubectl

  # authentication with google cloud, some credentials need it to have access to the google cloud account.
  # credentials will be available in the service-account.json file, the file will be decrypted and put in place before this step
  - gcloud auth activate-service-account --key-file service-account.json 
  
  # the project name is the project id on google cloud
  - gcloud config set project multi-k8s-344200
  
  # take the location from kubernetes engine, go to your cluster and you should see the location value
  - gcloud config set project multi-k8s-344200
  - gcloud config set compute/zone us-central1-c

  # the google cloud config needs to have the name of the cluster that it needs to work with.
  - gcloud container clusters get-credentials k8s-cluster 

  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t josua96/react-test -f  ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true josua96/react-test npm test

# custom deployment provider
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master