apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'joshuaenrique96@gmail.com'
    privateKeySecretRef: # lets encrypt send a secret key in the process of verifying if the cluster owns the domain
      name: letsencrypt-prod # we will not use this secret for any purpose
    # to specify that the cluster will perform the domain verification by reaching out lets encrypt, then lets encrypt will call an endpoint to verify
    # if the cluster really owns the domain.
    solvers:
      - http01:
          ingress:
            class: nginx